### ISSUE TITLE
DMN+ Sentiment analysis

### ISSUE THREAD

**Issue by MarcDjandji** [bill-kalog/rnn_sent#1]
Can you please share with us the accuracy for the sentiment analysis done on the Stanford Sentiment Treebank using the DMN+?

Thanks in advance

**Comment by bill-kalog** [comment]
Sure, you can find a few accuracy results in this report http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-217858  ~50%. Please bear in mind that the DMN+ is not implemented exactly as described in the paper and I also didn't do any actual hyper-parameter tuning so these can be just a few of the reasons that I don't reach the actual reported results...

**Comment by MarcDjandji** [comment]
Thanks a lot for the quick response 👍
